export interface ISymbol {
    name: string;
    symbol: string;
}

export const isEqual = (a: ISymbol, b: ISymbol):boolean => {
    return a.symbol === b.symbol;
}

export const symbols:Array<ISymbol> = [
   { symbol: "🙈", name: "See-No-Evil Monkey"},
{ symbol: "🙉", name: "Hear-No-Evil Monkey"},
{ symbol: "🙊", name: "Speak-No-Evil Monkey"},
{ symbol: "💥", name: "Collision"},
{ symbol: "💫", name: "Dizzy"},
{ symbol: "💦", name: "Sweat Droplets"},
{ symbol: "💨", name: "Dashing Away"},
{ symbol: "🐵", name: "Monkey Face"},
{ symbol: "🐒", name: "Monkey"},
{ symbol: "🦍", name: "Gorilla"},
{ symbol: "🦧", name: "Orangutan"},
{ symbol: "🐶", name: "Dog Face"},
{ symbol: "🐕", name: "Dog"},
{ symbol: "🦮", name: "Guide Dog"},
{ symbol: "🐕‍🦺", name: "Service Dog"},
{ symbol: "🐩", name: "Poodle"},
{ symbol: "🐺", name: "Wolf"},
{ symbol: "🦊", name: "Fox"},
{ symbol: "🦝", name: "Raccoon"},
{ symbol: "🐱", name: "Cat Face"},
{ symbol: "🐈", name: "Cat"},
{ symbol: "🐈‍⬛", name: "Black Cat"},
{ symbol: "🦁", name: "Lion"},
{ symbol: "🐯", name: "Tiger Face"},
{ symbol: "🐅", name: "Tiger"},
{ symbol: "🐆", name: "Leopard"},
{ symbol: "🐴", name: "Horse Face"},
{ symbol: "🐎", name: "Horse"},
{ symbol: "🦄", name: "Unicorn"},
{ symbol: "🦓", name: "Zebra"},
{ symbol: "🦌", name: "Deer"},
{ symbol: "🦬", name: "Bison"},
{ symbol: "🐮", name: "Cow Face"},
{ symbol: "🐂", name: "Ox"},
{ symbol: "🐃", name: "Water Buffalo"},
{ symbol: "🐄", name: "Cow"},
{ symbol: "🐷", name: "Pig Face"},
{ symbol: "🐖", name: "Pig"},
{ symbol: "🐗", name: "Boar"},
{ symbol: "🐽", name: "Pig Nose"},
{ symbol: "🐏", name: "Ram"},
{ symbol: "🐑", name: "Ewe"},
{ symbol: "🐐", name: "Goat"},
{ symbol: "🐪", name: "Camel"},
{ symbol: "🐫", name: "Two-Hump Camel"},
{ symbol: "🦙", name: "Llama"},
{ symbol: "🦒", name: "Giraffe"},
{ symbol: "🐘", name: "Elephant"},
{ symbol: "🦣", name: "Mammoth"},
{ symbol: "🦏", name: "Rhinoceros"},
{ symbol: "🦛", name: "Hippopotamus"},
{ symbol: "🐭", name: "Mouse Face"},
{ symbol: "🐁", name: "Mouse"},
{ symbol: "🐀", name: "Rat"},
{ symbol: "🐹", name: "Hamster"},
{ symbol: "🐰", name: "Rabbit Face"},
{ symbol: "🐇", name: "Rabbit"},
{ symbol: "🐿️", name: "Chipmunk"},
{ symbol: "🦫", name: "Beaver"},
{ symbol: "🦔", name: "Hedgehog"},
{ symbol: "🦇", name: "Bat"},
{ symbol: "🐻", name: "Bear"},
{ symbol: "🐻‍❄️", name: "Polar Bear"},
{ symbol: "🐨", name: "Koala"},
{ symbol: "🐼", name: "Panda"},
{ symbol: "🦥", name: "Sloth"},
{ symbol: "🦦", name: "Otter"},
{ symbol: "🦨", name: "Skunk"},
{ symbol: "🦘", name: "Kangaroo"},
{ symbol: "🦡", name: "Badger"},
{ symbol: "🐾", name: "Paw Prints"},
{ symbol: "🦃", name: "Turkey"},
{ symbol: "🐔", name: "Chicken"},
{ symbol: "🐓", name: "Rooster"},
{ symbol: "🐣", name: "Hatching Chick"},
{ symbol: "🐤", name: "Baby Chick"},
{ symbol: "🐥", name: "Front-Facing Baby Chick"},
{ symbol: "🐦", name: "Bird"},
{ symbol: "🐧", name: "Penguin"},
{ symbol: "🕊️", name: "Dove"},
{ symbol: "🦅", name: "Eagle"},
{ symbol: "🦆", name: "Duck"},
{ symbol: "🦢", name: "Swan"},
{ symbol: "🦉", name: "Owl"},
{ symbol: "🦤", name: "Dodo"},
{ symbol: "🪶", name: "Feather"},
{ symbol: "🦩", name: "Flamingo"},
{ symbol: "🦚", name: "Peacock"},
{ symbol: "🦜", name: "Parrot"},
{ symbol: "🐸", name: "Frog"},
{ symbol: "🐊", name: "Crocodile"},
{ symbol: "🐢", name: "Turtle"},
{ symbol: "🦎", name: "Lizard"},
{ symbol: "🐍", name: "Snake"},
{ symbol: "🐲", name: "Dragon Face"},
{ symbol: "🐉", name: "Dragon"},
{ symbol: "🦕", name: "Sauropod"},
{ symbol: "🦖", name: "T-Rex"},
{ symbol: "🐳", name: "Spouting Whale"},
{ symbol: "🐋", name: "Whale"},
{ symbol: "🐬", name: "Dolphin"},
{ symbol: "🦭", name: "Seal"},
{ symbol: "🐟", name: "Fish"},
{ symbol: "🐠", name: "Tropical Fish"},
{ symbol: "🐡", name: "Blowfish"},
{ symbol: "🦈", name: "Shark"},
{ symbol: "🐙", name: "Octopus"},
{ symbol: "🐚", name: "Spiral Shell"},
{ symbol: "🐌", name: "Snail"},
{ symbol: "🦋", name: "Butterfly"},
{ symbol: "🐛", name: "Bug"},
{ symbol: "🐜", name: "Ant"},
{ symbol: "🐝", name: "Honeybee"},
{ symbol: "🪲", name: "Beetle"},
{ symbol: "🐞", name: "Lady Beetle"},
{ symbol: "🦗", name: "Cricket"},
{ symbol: "🪳", name: "Cockroach"},
{ symbol: "🕷️", name: "Spider"},
{ symbol: "🕸️", name: "Spider Web"},
{ symbol: "🦂", name: "Scorpion"},
{ symbol: "🦟", name: "Mosquito"},
{ symbol: "🪰", name: "Fly"},
{ symbol: "🪱", name: "Worm"},
{ symbol: "🦠", name: "Microbe"},
{ symbol: "💐", name: "Bouquet"},
{ symbol: "🌸", name: "Cherry Blossom"},
{ symbol: "💮", name: "White Flower"},
{ symbol: "🏵️", name: "Rosette"},
{ symbol: "🌹", name: "Rose"},
{ symbol: "🥀", name: "Wilted Flower"},
{ symbol: "🌺", name: "Hibiscus"},
{ symbol: "🌻", name: "Sunflower"},
{ symbol: "🌼", name: "Blossom"},
{ symbol: "🌷", name: "Tulip"},
{ symbol: "🌱", name: "Seedling"},
{ symbol: "🪴", name: "Potted Plant"},
{ symbol: "🌲", name: "Evergreen Tree"},
{ symbol: "🌳", name: "Deciduous Tree"},
{ symbol: "🌴", name: "Palm Tree"},
{ symbol: "🌵", name: "Cactus"},
{ symbol: "🌾", name: "Sheaf of Rice"},
{ symbol: "🌿", name: "Herb"},
{ symbol: "☘️", name: "Shamrock"},
{ symbol: "🍀", name: "Four Leaf Clover"},
{ symbol: "🍁", name: "Maple Leaf"},
{ symbol: "🍂", name: "Fallen Leaf"},
{ symbol: "🍃", name: "Leaf Fluttering in Wind"},
{ symbol: "🍄", name: "Mushroom"},
{ symbol: "🌰", name: "Chestnut"},
{ symbol: "🦀", name: "Crab"},
{ symbol: "🦞", name: "Lobster"},
{ symbol: "🦐", name: "Shrimp"},
{ symbol: "🦑", name: "Squid"}
]